name: money_matrix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.0
  uuid: ^3.0.7
  shared_preferences: ^2.5.3
  razorpay_flutter: ^1.2.9
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0
  firebase_auth: ^6.1.2
  http: ^1.6.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  mysql1: ^0.20.0
  crypto: ^3.0.3
  socket_io_client: ^2.0.3 # Added for real-time game

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.jpeg"
